### ISSUE TITLE
Définir les attributs id comme des uuid sur Attachment et AnomalieAdresseBase

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/anomalieAdresse#103]
`AnomalieAdresseId` est défini comme un uuid.
`AttachmentId` est défini comme un uuid.

Comme ces valeurs d'id sont récupérées en sortie de POST sur AnomalieAdresse et Attachment il faut donc que :
-  `AnomalieAdresseBase.id` soit défini comme uuid
- `Attachment.id` soit  défini comme uuid

Par extension pour les futurs protocoles (Malfaçon entre autre), il est certainement préférable de le définir directement au niveau de la library **common** sur TroubleTicket et Attachment.

**Comment by ggrebert** [comment]
entièrement d'accord avec toi

**Comment by ericjacq92** [comment]
OK, je suis parfaitement en phase avec le PR sur common

**Comment by alexisthethe** [comment]
OK

**Comment by vmeunier** [comment]
La PR sur common ne fonctionne pas malheureusement car implique que tout id de toute entité "Addressable" soit uuid. Or les immeubles par exemple ne seront forcément pas en UUID.

Suite à la MAJ en OAS 3.0.3 je pensais avoir corrigé ce problème, mais à la génération on se rend compte que ça ne fonctionne pas.
