### ISSUE TITLE
AA Modification : remise en cohérence des possibilités de mise à blanc (complément issue 51)

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#117]
Bonjour,

Pour différentes raisons, les attributs pouvant être mis à blanc dans les AA Modification ("toBlank") ne sont pas alignés avec les champs IPE correspondants pouvant être vides (car facultatifs ou conditionnés).

1) Pouvez-vous supprimer les champs "toBlank" sur les critères d'erreur ci-dessous, qui correspondent à des champs obligatoires de la norme IPE 3.1/3.2, ne pouvant donc jamais être  vide dans l'IPE : 
     - building.address.city
     - building.address.postcode
     - building.address.code_insee
     - building.pm.id
=> en effet, il n'est pas souhaitable de donner la possibilité à l'OI d'injecter des erreurs dans son IPE (champs obligatoires mis à blanc)

2) Pouvez-vous ajouter des champs "toBlank" sur les critères d'erreur ci-dessous, qui correspondent à des champs conditionnés de la norme IPE 3.1/3.2, pouvant donc potentiellement être vides dans l'IPE : 
     - building.address.code_hexacle
     - building.address.streetNr

Note : les autres attributs sont OK (<=> ceux qui n'ont pas toBlank sont obligatoires dans l'IPE donc jamais vides, ceux qui ont toBlank sont facultatifs dans l'IPE donc potentiellement vides - corrigés via l'issue 51)

**Comment by richard-olvera** [comment]
j'ai ajouté dans la MR la suppression du toblank de building.housingsNumber 

c'est le seul champs où j'ai vu l'ajoute de toblank lors des merges de changement de version OpenAPI

**Comment by vmeunier** [comment]
Alors attention, là on a un gros problème métier de fond qui n'a absolument pas été corrigé.

En gros avant on avait une définition qui n'avait aucun sens où de ma compréhension tous les champs sont des "Issue" (et ce n'était absolument pas le cas tel que c'était écrit en spec OAS 3.1.0). Or, c'est bien ce qui a été indiqué en spec OAS 3.0.3, sauf que ça ne correspond pas au métier que vous vouliez avoir pour ces champs finalement, vu les problèmes avec le champ toBlank, remonté ici.

Mais dans ce cas, il n'y a pas que le toBlank qui pose problème, il manque le champ "description" pour l'intégralité des champs, puisque c'est dans Issue que provenait ce champ.

La PR a été validée et mergée alors qu'on a fait une remarque en ce sens.
