### ISSUE TITLE
Changer resolvedToInProgressDuration vers resolvedToAcknowledgedDuration

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#46]
Actuellement le compteur resolvedToInProgressDuration ne correspond à aucune transition de statut possible.
La transition ancienne RESOLVED => IN PROGRESS a été remplacée par RESOLVED => ACKNOWLEDGED, et il semble que le libellé du compteur n'ait pas été mis à jour dans la foulée.
Merci de modifier resolvedToInProgressDuration vers resolvedToAcknowledgedDuration

**Comment by ggrebert** [comment]
Plusieurs propositions:

1. garder l'état actuel car il existe aussi `acknowledgedDuration`.
2. remplacer `resolvedToInProgressDuration` par `resolvedToAcknowledgedDuration`
3. garder `resolvedToInProgressDuration` et ajouter `resolvedToAcknowledgedDuration`

il faudra proposer les 3 solutions aux opérateurs.

**Comment by JeanChristopheLacroix** [comment]
sol 1) acknowledgedDuration mesure la durée dans l'état ACKNOWLEDGED, ce qui est différent de de la durée dans l'état RESOLVED (quand il y a transition ensuite vers ACKNOWLEDGED

sol 3) Mais il n'y a pas de transition RESOLVED vers IN PROGRESS, c'était la cas avant mais plus maintenant

**Comment by ggrebert** [comment]
Orange propose la solution 1

**Comment by ericjacq92** [comment]
Réponse Bytel : proposition 2

**Comment by ggrebert** [comment]
> Pouvez-vous svp rappeler l'intérêt de ces champs `*Duration` ? Je ne comprends pas pourquoi ils doivent être remplis à chaque changement de status. Ceux-là devraient être automatiquement calculés en fonction des dates de changement d'état. Ne devraient-ils pas être des attributs "read-only" ?

c'est bien des champs read-only qui sont calculés automatiquement par l'OI

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 16/05 : à clôturer
=> il s'agit de la mise en conformité du swagger par rapport au word : ajustement suite à la suppression d'une transaction du diagramme de séquence (abandon de la transaction resolved -> inprogress pour resolved -> acknowledge)
