### ISSUE TITLE
Description unicité de la valeur de building.address.streetNrSuffix à modifier vers "Valeur spécifique à chaque immeuble"

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#47]
Dans l'existant, la description de l'unicité de la valeur pour building.address.streetNrSuffix est - à tort - Valeur commune pour tous les immeubles
En effet, la description format word du protocole AA prévoit que c'est une valeur spécifique
Merci de faire la correction.

![Description critères erreur Modification](https://github.com/before-interop/anomalieAdresse/assets/138661009/c3f3d9df-66ea-4301-bfa2-c9874ff95f26)
![Description criteres en masse dans word protocole AA](https://github.com/before-interop/anomalieAdresse/assets/138661009/d2945c16-e903-4449-aa4a-749eefb082fd)

**Comment by ggrebert** [comment]
Merge Request ouvert #50 
A proposer aux opérateurs.

**Comment by ericjacq92** [comment]
Réponse Bytel : d'accord pour le merge request proposé

**Comment by alexisthethe** [comment]
Axione : OK

**Comment by svernierAI** [comment]
Altitude: OK pour streetNrSuffix
               KO    pour streetType la voie étant commune à tous les IMB

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 16/05 : à clôturer
=> il s'agit de la mise en conformité du swagger par rapport au doc de description Word
