### ISSUE TITLE
Description unicité de la valeur de building.address.streetType à modifier vers "Valeur spécifique à chaque immeuble"

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#48]
Dans l'existant, la description de l'unicité de la valeur pour building.address.streetType est - à tort - Valeur commune pour tous les immeubles
En effet, la description format word du protocole AA prévoit que c'est une valeur spécifique
Merci de faire la correction.

![Description critères erreur Modification](https://github.com/before-interop/anomalieAdresse/assets/138661009/8685143e-1ef1-49fc-8e67-e83159f9269e)

![Description criteres en masse dans word protocole AA](https://github.com/before-interop/anomalieAdresse/assets/138661009/fe0229b0-8272-4c6b-8998-2acf8a4a7e4b)

**Comment by alexisthethe** [comment]
Axione : 
* OK pour "building.address.streetNrSuffix" qui devrait être "Valeur spécifique à chaque immeuble"
* NOK pour "building.address.streetType" qui devrait rester  "Valeur commune pour tous les immeubles". Il devrait avoir la même règle que "building.address.streetName" => à changer dans le protocole écrit au format word

**Comment by svernierAI** [comment]
Idem #47

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 16/05 : à clôturer
=> on ne modifie rien
