### ISSUE TITLE
Dans le type ano adresse Modification, ajouter la possibilité de mise à blanc pour le champs building name et les champs address streetNrSuffix / streetType / code_hexacle_voie / code_ban

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#51]
Dans l'existant / type ano adresse Modification, les champs suivants ne peuvent pas être mis à blanc (indicateur toBlank comme le code Rivoli), alors que dans l'IPE 3.1, ces champs sont facultatifs et peuvent être vides ==> merci d'ajouter cette [possibilité](url)

building.name
building.address.streetNrSuffix
building.address.streetType
building.address.code_hexacle_voie
building.address.code_ban

**Comment by JeanChristopheLacroix** [comment]
[Flux interop PM 31_20191204v2.xlsx](https://github.com/before-interop/anomalieAdresse/files/14559955/Flux.interop.PM.31_20191204v2.xlsx)

**Comment by ericjacq92** [comment]
Réponse Bytel : Ok pour la mise à jour

**Comment by alexisthethe** [comment]
Axione : OK

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 16/05 : à clôturer
=> il s'agit de la mise en conformité du swagger par rapport au doc de description Word
