### ISSUE TITLE
Type ano adresse création / tableau geographicLocation à limiter à 1 élément

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#53]
Dans l'existant / Type ano adresse création : le champ geographicLocation est un tableau >= 1 items, alors que ce type d'ano ne concerne qu'un seul IMB
==> merci de mettre tableau de 1 élément

**Comment by ggrebert** [comment]
L'objectif d'en faire un tableau, c'est de pouvoir fournir plusieurs projections.

ex; `RFG93` et `WGS84`

**Comment by JeanChristopheLacroix** [comment]
Ok je comprends mieux ..

**Comment by ggrebert** [comment]
On peut clôturer l'issue ?

**Comment by JeanChristopheLacroix** [comment]
OK avec la réponse de Geoffrey G.
