### ISSUE TITLE
Ano en masse : faire en sorte que les critères d'erreur communs à tous les IMB ne soient précisés qu'une seule fois

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#56]
Dans l'existant, les critères d'erreur suivants sont communs à tous les IMB, alors qu'ils sont déclarés comme étant des tableaux sans limite de taille: 
building.address.streetname, 
building.address.postcode, 
building.address.city,
building.address.streetType,
building.address.code_insee,
building.address.code_hexacle_voie,

==> merci de faire en sorte que l'OC soit contraint à ne saisir qu'une seule fois les valeurs de ces critères

**Comment by ggrebert** [comment]
2 possibilités:

1. modifier le type du champs `value` pour le remplacer de `array<string>` à `string`
2. ajouter un critère de validation sur `value`: `< 2 items`

**Comment by JeanChristopheLacroix** [comment]
ORANGE a une préférence pour la solution 1, + lisible et + simple

**Comment by alexisthethe** [comment]
Axione : OK pour la solution 1

**Comment by svernierAI** [comment]
Seuls les attributs communs à tous les IMB doivent être définis de type Value
