### ISSUE TITLE
Complexity : prévoir la valeur vide pour les anomalies en masse

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#63]
a description word du protocole prévoit que la complexité simple/complexe ne soit définie que pour les anomalies unitaires.
La complexité n'est pas définie pour les anos en masse
Cf PJ
Merci de prévoir la possibilité de mettre un valeur vide, ça n'est pas prévu dans la version actuelle du swagger

![image](https://github.com/before-interop/anomalieAdresse/assets/138661009/34bf45ad-2367-486e-bdc2-9548821e81aa)

![image](https://github.com/before-interop/anomalieAdresse/assets/138661009/a1d730c7-0e76-4743-b5a9-beb553e02bf3)

**Comment by ggrebert** [comment]
C'est une valeur "read-only" qui est géré par l'OI.

2 possibilités:

1. Ajouter la valeur `MULTI` pour gérer le cas des anomalies en masse
2. Mettre les anomalies en masse à la valeur `COMPLEX`

**Comment by JeanChristopheLacroix** [comment]
Seule la proposition 1 pourrait convenir.

La 2 va impacter les KPI et serait aussi non conforme à la décision Arcep.
3 types d’anomalies sont définies dans la décision arcep :
-	Unitaire simple
-	Unitaire complexe
-	En masse

Il faut pouvoir retrouver ces 3 types au niveau de API, pour que le traitant (quand on est OI) s’y retrouve, pour que les compteurs de délais soient bien distincts, pour que des KPI par types soient possibles…
Vision OC c’est pareil mettre complexe pour une demande en masse reviendra à confondre 2 types d’anomalies.

**Comment by ggrebert** [comment]
Il ne faut pas oublier qu'il existe déjà un attribut pour différencier les anomalies en masse: `sizeRefs`

**Comment by JeanChristopheLacroix** [comment]
Oui d'accord, mais une anomalie en masse complexe ça ne veut rien dire, simple/complex n'a de sens que pour les unitaires.

**Comment by ggrebert** [comment]
OK pour la proposition 1.
Par contre, elle engendre un breaking change

**Comment by ericjacq92** [comment]
Réponse Bytel :

La modification en masse est une modification qui s'applique sur plusieurs refImmeuble au lieu d'une seule ==> elle devrait être qualifiable en SIMPLE ou COMPLEX. On peut adopter COMPLEX puisqu'il est convenu qu'en masse, il est convenu que le délai soit étendu.

**Comment by MARIEPHAM** [comment]
Réponse Axione : en phase avec la nécessité d'**ajouter une 3è valeur** de _complexity_ pour les demandes en masse.

On ne peut pas considérer qu'une demande en masse correspond à un cas complexe puisque le délai de la décision Arcep n'est pas le même. Et l'utilisation d'un autre champ pour distinguer les demandes en masse (autre proposition ci-dessus) complexifierait inutilement le calcul des indicateurs.

**Comment by svernierAI** [comment]
Altitude : Une anomalie en masse étant déjà typée, je pencherai plus pour indiquer COMPLEX

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 16/05 : à clôturer
=>La valeur de la complexité pour les anomalies en masse sera "MASSE"
