### ISSUE TITLE
Type Ano UpdateNbLogements : supprimer la possibilité de mise à blanc du nombre de logements cible

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#65]
Dans l'existant / type ano adresse UpdateNbLogements:

Il est possible de demander la mise à blanc du nombre de logements de l'IPE via le booleen toBlank.
Or dans l'IPE, le champ NombreLogementsAdresseIPE est obligatoire ==> il ne peut pas être vide.

==> merci de supprimer la possibilité de mise à blanc du nombre de logements dans le swagger 
<=> supprimer le champ toBlank pour building.housingsNumber.

Cette issue vient en remplacement de l'issue 52, qui est obsolète.

**Comment by ericjacq92** [comment]
Réponse Bytel : Ok pour supprimer le champ toBlank pour building.housingsNumber.

**Comment by alexisthethe** [comment]
Axione: OK

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 16/05 : à clôturer
=> il s'agit de la mise en conformité du swagger par rapport au doc de description Word
