### ISSUE TITLE
Ecart entre spec et swagger sur attribut immeubleNeuf

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/anomalieAdresse#66]
Remontée Bytel :
Dans la spec word, la définition de l'attribut ImmeubleNeuf indique trois possibilités :
0/1/2 ==> 0=Non ; 1=Oui (avec cuivre) ; 2=Oui (ZLIN=sans cuivre)

Dans le swagger on a défini un attribut`building`.`newConstruction `de type booléen qui ne permet pas de distinguer les cas "avec cuivre" et "sans cuivre". Peut on transformer le type booléen en texte énuméré pour couvrir les 3 cas possibles.

**Comment by alexisthethe** [comment]
Axione: OK

**Comment by JeanChristopheLacroix** [comment]
ORANGE : NOK
 c’est une donnée propre à l’OI, l’OC n’en n’est pas maitre et ne l’a pas forcément (données IPE « SansCuivre » facultative)

**Comment by ggrebert** [comment]
@JeanChristopheLacroix
Quoi qu'il en soit, il y a quand même une erreur: Si c'est une donnée propre à l'OI, la propriété devrait être en `read-only`

Je vous laisse en opérateur décider qui a raison

**Comment by JeanChristopheLacroix** [comment]
Ce que l'OC doit préciser : si l'IMB est neuf ou non ==> ne doit donc PAS être en read_only
Ce que l'OC ne peut pas préciser : si l'IMB est avec ou sans Cuivre (car la donnée est propre à l'OI, et est facultative dans l'IPE)

**Comment by ggrebert** [comment]
Donc je fais quoi ?
Il n'y a aucune notion de *Zlin* dans le protocole actuellement.
C'est peut être de document word qui est faux

**Comment by ericjacq92** [comment]
BYTEL :
Ma demande était liée à la mise en conformité par rapport à la spec word du protocole, et à la demande de mon métier qui a bien prévu de pousser ce niveau de granularité : 

![image](https://github.com/before-interop/anomalieAdresse/assets/134420338/92e0337d-2f16-4c6d-bd6b-efb410bed58c)
