### ISSUE TITLE
Incohérence dans les type définis classe parente -  classe fille

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/anomalieAdresse#73]
Postée par Bytel.
Cette issue est remontée par nos équipe technique en charge d'implémenter le swagger.
Ce problème déclenche des erreurs bloquantes dans les générateurs de code utilisés à partir du swagger (codeGen, OpenAPI Generator).

Il y a des incohérences entre les définition au niveau des schémas des objets.
Par exemple sur le @type défini en '**AnomalieAdresseCreation**' dans le discriminator de OneOfAnomalieAdresse, et le @type défini en "**AnomalieAdresse.creation**" au niveau du schéma de la classe fille AnomalieAdresseCreation  :
```
  schemas:
    OneOfAnomalieAdresse:
      oneOf:
        - $ref: "#/components/schemas/AnomalieAdresseCreation"
        - $ref: "#/components/schemas/AnomalieAdresseNewBuilding"
        - $ref: "#/components/schemas/AnomalieAdresseUpdateImb"
        - $ref: "#/components/schemas/AnomalieAdresseUpdateNbLogements"
      discriminator:
        propertyName: "@type"
        mapping:
          AnomalieAdresseCreation: "#/components/schemas/AnomalieAdresseCreation"
          AnomalieAdresseNewBuilding: "#/components/schemas/AnomalieAdresseNewBuilding"
          AnomalieAdresse.modification: "#/components/schemas/AnomalieAdresseUpdateImb"
          AnomalieAdresse.nbLogements: "#/components/schemas/AnomalieAdresseUpdateNbLogements"
```
et :
```
    AnomalieAdresseCreation:
      ...
      required:
        - building
      properties:
        "@type":
          const: AnomalieAdresse.creation
```

**Comment by ggrebert** [comment]
@ericjacq92 pourrais tu valider la proposition de fix STP ? : https://github.com/before-interop/anomalieAdresse/pull/74

**Comment by richard-olvera** [comment]
validation interop du 7 juin
