### ISSUE TITLE
Incohérence de définition de "priority" et "ticketType" dans l'héritage 

### ISSUE THREAD

**Issue by fgibello** [before-interop/anomalieAdresse#81]
priority :

Dans "AnomalieAdresseBase", on retrouve pour le champ "priority" une "enum" alors que, dans "TroubleTicket", le type du champ est "string".
Dans la description, il faudrait ajouter "critical" également : s'il y a une "enum", il faut que tous les choix y soient présents.

ticketType :

Dans "AnomalieAdresseBase", on retrouve pour le champ "ticketType" une "enum" alors que, dans "TroubleTicket", le type du champ est "string".

**Comment by ggrebert** [comment]
* Le `type` est bien `string`.

  `enum` représente les valeurs possible. Il est possible d'avoir un `enum` avec un `type` à la valeur `integer`.

  Doc openapi: https://swagger.io/docs/specification/data-models/enums/

* `CRITICAL` n'a pas été proposée comme valeur possible pour `priority` dans le cadre d'AnomalieAdresse. Si il est présenté en exemple dans la description c'est que celle-ci est héritée de `TroubleTicket`. Il est possible de :
  1. Proposer la valeur `CRITICAL` en Interop
  2. Surcharger la description de `priority`
  3. Laisser comme tel

**Comment by ggrebert** [comment]
Peut-on clôturer l'issue ?

**Comment by richard-olvera** [comment]
rejeter en interop du 7 juin
