### ISSUE TITLE
Définitions incomplètes IssueArray

### ISSUE THREAD

**Issue by fgibello** [before-interop/anomalieAdresse#82]
L'attribut value est un array mais sans préciser les items : il manque le contenu du tableau.
![issue](https://github.com/before-interop/anomalieAdresse/assets/159422683/0266f030-01b6-4361-a197-d86c19dfae32)

**Comment by ggrebert** [comment]
En effet, cela représente `array<any>`. cette classe est abstraite et est toujours héritée lorsqu'elle est utilisée.

Exemple d'utilisation de cette classe avec `building.geographicLocations` et `building.name`:

```yaml
properties:
  "building.geographicLocations":
    $ref: "#/components/schemas/IssueArray"
    description: Liste des coordonnées géographiques de l'adresse corrigée.
    properties:
      value:
        items:
          $ref: https://raw.githubusercontent.com/before-interop/common/main/common/schemas/Interop.openapi.yaml#/components/schemas/GeographicPoint
  "building.name":
    $ref: "#/components/schemas/IssueArray"
    description: |
      Nom du bâtiment.

      Ce champ est nommé `BatimentImmeuble` dans le fichier IPE.
    properties:
      value:
        items:
          $ref: https://raw.githubusercontent.com/before-interop/common/main/common/schemas/Interop.openapi.yaml#/components/schemas/Building/properties/name
```

**Comment by ggrebert** [comment]
@ericjacq92 a clôturé l'issue #84 , je pense qu'on peut donc clôturer celle-ci aussi

Qu'en penses tu @fgibello ?

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 03/10/2024 : à cloturer

**Comment by JeanChristopheLacroix** [comment]
Décision Interop du 03/10/2024 : à clôturer
