### ISSUE TITLE
Anomalies Modification : mettre en cohérence les combinaisons de critères d'erreur en regard de la définition du signalement en masse

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#86]
La définition swagger de "AnomalieAdresse.modification" actuelle est : Anomalie qui permet de mettre à jour un ou plusieurs attributs sur un ou plusieurs immeubles.
![image](https://github.com/before-interop/anomalieAdresse/assets/138661009/dcd125a2-9bb0-4d77-90e6-2aa28834862f)

Elle devrait plutot être :
Anomalie qui permet de mettre à jour :
	- En unitaire : un ou plusieurs attributs sur un seul immeuble.
	- En masse : un seul attribut sur plusieurs immeubles.

En effet, la définition swagger de "Signalement en masse" est : 
par exemple liste d'anomalies détectées par contrôles informatisés ayant un critère commun (anomalie sur un même champ). Il s'agit d'un signalement unitaire impactant deux lignes IPE ou plus. Certains critères devront concerner la même zone géographique.
![image](https://github.com/before-interop/anomalieAdresse/assets/138661009/de7649d8-ae80-4a77-92de-57084b1e454b)

==> Quand l'ano modification est en masse, on ne doit pas pouvoir combiner les critères d'erreur car une ano en masse porte par définition sur un critère d'erreur commun aux IMBs : 1 seul critère doit être  renseigné

**Comment by ericjacq92** [comment]
On peut avoir tous les immeubles d'une rue erronée pour les attributs  'nom de voie', et 'code postal' ==> dans ce cas on doit pouvoir définir l'ensemble des critères communs à modifier.
