### ISSUE TITLE
Ajouter valorisation de compteur resolvedToAcknowledgedDuration (#46) dans la description de la transition RESOLVED => ACKNOWLEDGED

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#88]
La description actuelle de la transition RESOLVED => ACKNOWLEDGED ne mentionne pas - à tort - la valorisation du compteur  resolvedToAcknowledgedDuration (aujourd'hui nommé resolvedToInProgressDuration, à renommer via issue 46)

![image](https://github.com/before-interop/anomalieAdresse/assets/138661009/3c5a850e-eebc-4c58-a434-1e80cfd9bd86)

**Comment by alexisthethe** [comment]
Je suis d'accord.
J'irai même plus loin. Ne faudrait-il pas plutôt des noms de variables "duration" plus claires avec un sens métier.
Dans ce cas ici: "ResolutionRefusalDuration"

**Comment by JeanChristopheLacroix** [comment]
Clôturée car mise à jour effectuée dans le word (dernière version validée en Interop le 6 sept 2024).
