### ISSUE TITLE
Ajouter valorisation de compteur resolvedToClosedDuration dans la description de la transition RESOLVED => CLOSED

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/anomalieAdresse#89]
Dans le swagger, la description de la transition RESOLVED => CLOSED ne mentionne pas - à tort - la valorisation du compteur resolvedToClosedDuration 

![image](https://github.com/before-interop/anomalieAdresse/assets/138661009/d8ed1b19-ec87-44a1-a619-40b3d94af092)

**Comment by alexisthethe** [comment]
OK

**Comment by JeanChristopheLacroix** [comment]
Clôturée car mise à jour effectuée dans le word (dernière version validée en Interop le 6 sept 2024).
