### ISSUE TITLE
Transitions incorrectes dans les exemples du README

### ISSUE THREAD

**Issue by NinjaKinshasa** [before-interop/anomalieAdresse#94]
Le README présente des exemples incluant des transitions d'état incompatibles avec le graphe de machine à état.

1.  [CLOSED -> REJECTED](https://github.com/before-interop/anomalieAdresse?tab=readme-ov-file#cas-nominal)
2.  [CLOSED -> IN_PROGRESS](https://github.com/before-interop/anomalieAdresse?tab=readme-ov-file#refus-de-la-r%C3%A9solution-par-loc)
3.  [CLOSED -> IN_PROGRESS](https://github.com/before-interop/anomalieAdresse?tab=readme-ov-file#d%C3%A9lai-informations-compl%C3%A9mentaires-d%C3%A9pass%C3%A9)
4.  [RESOLVED -> IN_PROGRESS](https://github.com/before-interop/anomalieAdresse?tab=readme-ov-file#refuser-la-r%C3%A9solution-dune-anomalie)

Il faut mettre à jour les exemples.

**Comment by alexisthethe** [comment]
je suis d'accord
